# Generated by Django 4.2.4 on 2023-09-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='img',
            new_name='criteria',
        ),
    ]
