# Generated by Django 4.2.4 on 2023-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_companyprofile_companydp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('MCA', 'MCA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(blank=True, choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('Integrated MCA', 'Integrated MCA'), ('Regular MCA', 'Regular MCA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.CharField(blank=True, choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7'), ('Semester 8', 'Semester 8'), ('Semester 9', 'Semester 9'), ('Semester 10', 'Semester 10')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
