# Generated by Django 4.2.4 on 2023-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_students_course_alter_students_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
