# Generated by Django 4.2.5 on 2023-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_adminstudent_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
