# Generated by Django 4.2.5 on 2023-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_adminstudent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=10)),
                ('current_semester', models.CharField(max_length=10)),
                ('cgpa', models.FloatField()),
                ('twelfth_institution', models.CharField(max_length=100)),
                ('twelfth_cgpa', models.FloatField()),
                ('twelfth_course', models.CharField(max_length=100)),
                ('twelfth_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
                ('tenth_institution', models.CharField(max_length=100)),
                ('tenth_cgpa', models.FloatField()),
                ('tenth_course', models.CharField(max_length=100)),
                ('tenth_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
                ('ug_institution', models.CharField(max_length=100)),
                ('ug_cgpa', models.FloatField()),
                ('ug_course', models.CharField(max_length=100)),
                ('ug_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
