# Generated by Django 4.2.5 on 2023-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_jobs_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
