# Generated by Django 4.2.5 on 2023-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_studentprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('MCA', 'MCA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('Integrated MCA', 'Integrated MCA'), ('Regular MCA', 'Regular MCA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
