# Generated by Django 4.2.5 on 2023-10-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_studentprofile_cgpa_alter_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='adminstu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adminstudent'),
        ),
    ]
