# Generated by Django 4.2.5 on 2023-10-04 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0029_studentprofile_adminstu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstudent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentt_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
