# Generated by Django 4.2.5 on 2023-10-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_companyapprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
