# Generated by Django 4.2.5 on 2023-10-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_studentprofile_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
