# Generated by Django 4.2.5 on 2023-10-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0048_alter_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
