# Generated by Django 4.2.5 on 2023-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='ug_cgpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
