# Generated by Django 4.2.5 on 2023-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_alter_studentprofile_dob_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, default='YYYY-MM-DD', max_length=10, null=True),
        ),
    ]
