# Generated by Django 4.2.5 on 2023-10-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_jobapplication_stuprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
