# Generated by Django 4.2.5 on 2023-10-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
