# Generated by Django 4.2.5 on 2023-10-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_alter_studentprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
    ]
