# Generated by Django 4.2.5 on 2023-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_jobapplication_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
