# Generated by Django 4.2.5 on 2023-10-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_remove_jobapplication_religion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='cgpa',
            new_name='c_cgpa',
        ),
    ]
