# Generated by Django 4.2.5 on 2023-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_rename_cgpa_studentprofile_c_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Electronics and Communication engineering', 'Electronics and Communication engineering'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Integrated MCA', 'Integrated MCA'), ('Regular MCA', 'Regular MCA')], max_length=700, null=True),
        ),
    ]
