# Generated by Django 4.2.5 on 2023-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_alter_studentprofile_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='companyname',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='jobname',
            new_name='jname',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='c_cgpa',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
