# Generated by Django 4.2.5 on 2023-10-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_alter_jobapplication_cname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='c_cgpa',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
