# Generated by Django 5.0.1 on 2024-01-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_jobs_required_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('title', models.CharField(max_length=100, null=True)),
                ('durno', models.IntegerField(blank=True, null=True)),
                ('durex', models.CharField(max_length=100, null=True)),
                ('stdate', models.DateField()),
                ('enddate', models.DateField()),
                ('caption', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('category', models.CharField(max_length=100, null=True)),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('moreinfo', models.TextField(null=True)),
                ('whoapply', models.TextField(null=True)),
                ('onoff', models.CharField(max_length=100, null=True)),
                ('certificate', models.BooleanField(default=True, verbose_name='status')),
                ('tim', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
