# Generated by Django 5.0.1 on 2024-01-30 04:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_internship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('interns', models.CharField(max_length=100, null=True)),
                ('internname', models.CharField(max_length=100, null=True)),
                ('interndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='classdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('interndate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('interntimes', models.CharField(default=0, max_length=100, null=True)),
                ('candi_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.internship')),
            ],
        ),
    ]
