# Generated by Django 5.0.1 on 2024-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_studentprofile_is_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
