# Generated by Django 5.0.1 on 2024-02-04 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_rename_passout_studentprofile_passout_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_alumni', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('reset_password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('course', models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('MCA', 'MCA')], max_length=50, null=True)),
                ('department', models.CharField(blank=True, choices=[('Electronics and Communication engineering', 'Electronics and Communication engineering'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Integrated MCA', 'Integrated MCA'), ('Regular MCA', 'Regular MCA')], max_length=700, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('passout_year', models.CharField(blank=True, max_length=10, null=True)),
                ('current_semester', models.CharField(blank=True, max_length=10, null=True)),
                ('c_cgpa', models.FloatField(blank=True, max_length=10, null=True)),
                ('c_backlog', models.CharField(blank=True, max_length=100, null=True)),
                ('twelfth_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('twelfth_cgpa', models.FloatField(blank=True, null=True)),
                ('twelfth_course', models.CharField(blank=True, max_length=100, null=True)),
                ('twelfth_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
                ('tenth_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('tenth_cgpa', models.FloatField(blank=True, null=True)),
                ('tenth_course', models.CharField(blank=True, max_length=100, null=True)),
                ('tenth_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
                ('ug_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_cgpa', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_course', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_certificate_upload', models.FileField(blank=True, null=True, upload_to='images/')),
                ('adminstu', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adminstudent')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
