# Generated by Django 5.0.1 on 2024-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('title', models.CharField(max_length=100, null=True)),
                ('stdate', models.DateField()),
                ('caption', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('moreinfo', models.TextField(null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('certificate', models.BooleanField(default=True, verbose_name='status')),
            ],
        ),
    ]
