# Generated by Django 5.0.1 on 2024-02-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_rename_img_resume1_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume1',
            name='status',
        ),
        migrations.AlterField(
            model_name='resume1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_images/'),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='resume_pdfs/'),
        ),
        migrations.AlterField(
            model_name='resume1',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='resume_videos/'),
        ),
    ]
