# Generated by Django 5.0.1 on 2024-02-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0102_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alumni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.alumni'),
        ),
    ]
