# Generated by Django 5.0.1 on 2024-02-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_exceldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='admission_number',
            new_name='admission_no',
        ),
    ]
