# Generated by Django 5.0.1 on 2024-03-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_examschedule_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resume1',
            new_name='resumeadmin',
        ),
    ]
