# Generated by Django 5.0.1 on 2024-03-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0115_rename_resume1_resumeadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstudent',
            name='course_end_date',
            field=models.DateField(null=True),
        ),
    ]
