# Generated by Django 5.0.1 on 2024-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_adminstudent_course_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='passout_year',
            field=models.DateField(null=True),
        ),
    ]
