# Generated by Django 5.0.1 on 2024-03-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0124_alter_questionn_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
    ]
