# Generated by Django 5.0.1 on 2024-03-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0125_addaptitude_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaptitude',
            name='job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
    ]
