# Generated by Django 5.0.3 on 2024-03-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0132_remove_questionn_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='jobb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
    ]
