# Generated by Django 5.0.3 on 2024-03-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0136_delete_addaptitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAptitude',
            fields=[
                ('aptitude', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('link', models.URLField()),
                ('login_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('regulations', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('company_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
            ],
        ),
    ]
