# Generated by Django 5.0.3 on 2024-03-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0140_alter_questionn_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionn',
            name='company_profile',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
    ]
