# Generated by Django 5.0.3 on 2024-03-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0149_remove_addaptitude_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaptitude',
            name='job_id',
        ),
        migrations.AddField(
            model_name='addaptitude',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobapplication'),
        ),
    ]
