# Generated by Django 5.0.3 on 2024-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0153_addaptitude_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
