# Generated by Django 5.0.3 on 2024-03-19 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0154_blogcontent_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
    ]
