# Generated by Django 5.0.3 on 2024-03-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0156_examresponse_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_batch', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_name', models.CharField(max_length=255)),
                ('aptitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.addaptitude')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.questionn')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.examresponse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
            ],
        ),
    ]
