# Generated by Django 5.0.3 on 2024-03-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0158_responsenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsenew',
            name='question',
        ),
    ]
