# Generated by Django 5.0.3 on 2024-03-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0159_remove_responsenew_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsenew',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='responsenew',
            name='exam_response',
        ),
        migrations.RemoveField(
            model_name='responsenew',
            name='student',
        ),
    ]
