# Generated by Django 5.0.3 on 2024-03-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0161_remove_testresult_aptitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
