# Generated by Django 5.0.3 on 2024-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0163_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
