# Generated by Django 5.0.3 on 2024-03-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0175_resultaptitude_delete_aptresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptdResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_department', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=20)),
                ('total_marks', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
            ],
        ),
    ]
