# Generated by Django 5.0.3 on 2024-04-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0177_aptdresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('ampm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('interview_type', models.CharField(max_length=50)),
                ('interview_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('interview_link_location', models.CharField(max_length=255)),
                ('interview_duration', models.IntegerField()),
                ('interviewer_info', models.TextField()),
                ('instruction_requirements', models.FileField(blank=True, null=True, upload_to='instruction_requirements/')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
                ('shortlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.shortlistedstudent')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
            ],
        ),
    ]
