# Generated by Django 5.0.3 on 2024-04-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0178_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='student',
            new_name='studentt',
        ),
    ]
