# Generated by Django 5.0.3 on 2024-04-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0179_rename_student_interview_studentt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='studentt',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='interview',
            name='shortlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.aptdresult'),
        ),
    ]
