# Generated by Django 5.0.3 on 2024-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0181_remove_interview_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptdresult',
            name='student_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
