# Generated by Django 5.0.3 on 2024-04-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0183_addaptitude_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptdresult',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile'),
        ),
    ]
