# Generated by Django 5.0.1 on 2024-04-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0188_jobapplication_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
    ]
