# Generated by Django 5.0.1 on 2024-04-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0189_addaptitude_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
    ]
