# Generated by Django 5.0.1 on 2024-04-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0190_remove_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
