# Generated by Django 4.2.4 on 2023-09-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
