# Generated by Django 4.2.4 on 2023-09-20 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0010_companyprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StuProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='default', max_length=100)),
                ('course', models.CharField(default='default', max_length=100)),
                ('contact', models.CharField(default='default', max_length=15)),
                ('addressline1', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(default='www.example.com', max_length=100)),
                ('city', models.CharField(default=' eg: Kochi', max_length=100)),
                ('district', models.CharField(default=' eg:Ernakulam', max_length=100)),
                ('state', models.CharField(default=' eg:Kerala ', max_length=100)),
                ('country', models.CharField(default=' eg: India', max_length=100)),
                ('pincode', models.CharField(default=' eg:686403', max_length=15)),
                ('companydp', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
