# Generated by Django 4.2.5 on 2023-09-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_student_stuprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
