# Generated by Django 4.2.5 on 2023-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_remove_companyprofile_ceo_remove_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='companyname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
