# Generated by Django 4.2.5 on 2023-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_adminstudent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, default=' ', max_length=254, null=True),
        ),
    ]
