# Generated by Django 4.2.5 on 2023-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_editrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editrequest',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
    ]
