# Generated by Django 4.2.5 on 2023-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_editrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='required_current_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='required_tenth_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='required_twelfth_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
