# Generated by Django 4.2.5 on 2023-10-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0038_jobs_required_current_cgpa_jobs_required_tenth_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
