# Generated by Django 4.2.5 on 2023-10-06 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0041_alter_companyprofile_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='required_current_cgpa',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='required_tenth_cgpa',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='required_twelfth_cgpa',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
        migrations.AlterField(
            model_name='adminstudent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentt_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact',
            field=models.CharField(default=' ', max_length=15),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='CompanyApprove',
        ),
        migrations.DeleteModel(
            name='EditRequest',
        ),
    ]
