# Generated by Django 4.2.5 on 2023-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_jobs_required_current_cgpa_jobs_required_tenth_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='reset_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
