# Generated by Django 4.2.5 on 2023-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_companyprofile_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
