# Generated by Django 4.2.5 on 2023-10-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_rename_tenth_course_jobapplication_c_backlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='stuprof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile'),
        ),
    ]
