# Generated by Django 4.2.5 on 2023-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_alter_studentprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
