# Generated by Django 4.2.5 on 2023-10-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_alter_jobapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='companyname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
