# Generated by Django 4.2.5 on 2023-10-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0062_remove_jobapplication_adminstu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.jobs'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stuprof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
