# Generated by Django 4.2.5 on 2023-10-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_alter_jobapplication_c_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
