# Generated by Django 4.2.5 on 2023-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0071_jobapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='required_backlog',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
