# Generated by Django 5.0.1 on 2024-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_internship_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='category',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='durex',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='durno',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='location',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='onoff',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='stipend',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='tim',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='whoapply',
        ),
    ]
