# Generated by Django 5.0.1 on 2024-01-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_videolibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolibrary',
            name='pdf',
        ),
    ]
