# Generated by Django 5.0.1 on 2024-01-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_remove_videolibrary_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ccontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('cname', models.CharField(max_length=100, null=True)),
                ('name', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
    ]
