# Generated by Django 5.0.1 on 2024-02-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_remove_ccontent_status_ccontent_udate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccontent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
