# Generated by Django 5.0.1 on 2024-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_likedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedcontent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
