# Generated by Django 5.0.1 on 2024-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_remove_resume1_status_alter_resume1_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('skill1', models.CharField(max_length=255)),
                ('skill2', models.CharField(max_length=255)),
                ('skill3', models.CharField(max_length=255)),
                ('skill4', models.CharField(max_length=255)),
                ('skill5', models.CharField(max_length=255)),
                ('degree1', models.CharField(max_length=255)),
                ('college1', models.CharField(max_length=255)),
                ('year1', models.CharField(max_length=4)),
                ('degree2', models.CharField(max_length=255)),
                ('college2', models.CharField(max_length=255)),
                ('year2', models.CharField(max_length=4)),
                ('degree3', models.CharField(max_length=255)),
                ('college3', models.CharField(max_length=255)),
                ('year3', models.CharField(max_length=4)),
                ('lang1', models.CharField(max_length=255)),
                ('lang2', models.CharField(max_length=255)),
                ('lang3', models.CharField(max_length=255)),
                ('project1', models.CharField(max_length=255)),
                ('durat1', models.CharField(max_length=255)),
                ('desc1', models.TextField()),
                ('project2', models.CharField(max_length=255)),
                ('durat2', models.CharField(max_length=255)),
                ('desc2', models.TextField()),
                ('company1', models.CharField(max_length=255)),
                ('post1', models.CharField(max_length=255)),
                ('duration1', models.CharField(max_length=255)),
                ('lin11', models.TextField()),
                ('company2', models.CharField(max_length=255)),
                ('post2', models.CharField(max_length=255)),
                ('duration2', models.CharField(max_length=255)),
                ('lin21', models.TextField()),
                ('ach1', models.CharField(max_length=255)),
                ('ach2', models.CharField(max_length=255)),
                ('ach3', models.CharField(max_length=255)),
            ],
        ),
    ]
