# Generated by Django 5.0.1 on 2024-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0098_resumebuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
