# Generated by Django 5.0.1 on 2024-02-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.alumni'),
        ),
    ]
