# Generated by Django 5.0.1 on 2024-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_blogcontent_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('event_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10)),
                ('link', models.URLField()),
            ],
        ),
    ]
