# Generated by Django 5.0.1 on 2024-02-20 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
