# Generated by Django 5.0.1 on 2024-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0108_alter_exceldata_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAptitude',
            fields=[
                ('aptitude', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_and_time', models.DateTimeField()),
                ('link', models.URLField()),
                ('login_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('regulations', models.TextField()),
            ],
        ),
    ]
