# Generated by Django 5.0.1 on 2024-02-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_addaptitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='company_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
        migrations.AddField(
            model_name='addaptitude',
            name='companyname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
