# Generated by Django 5.0.1 on 2024-02-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_addaptitude_company_profile_addaptitude_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
