# Generated by Django 5.0.1 on 2024-03-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0122_questionn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionn',
            old_name='title',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='questionn',
            name='id',
        ),
        migrations.AddField(
            model_name='questionn',
            name='exam_title',
            field=models.CharField(default='Aptitude', max_length=255),
        ),
        migrations.AddField(
            model_name='questionn',
            name='question',
            field=models.CharField(default='question', max_length=255),
        ),
        migrations.AddField(
            model_name='questionn',
            name='question_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='questionn',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
