# Generated by Django 5.0.1 on 2024-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0123_rename_title_questionn_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionn',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
