# Generated by Django 5.0.1 on 2024-03-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0127_alter_addaptitude_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addaptitude',
            old_name='job',
            new_name='jobb',
        ),
    ]
