# Generated by Django 5.0.1 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0128_rename_job_addaptitude_jobb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaptitude',
            name='jobb',
        ),
    ]
