# Generated by Django 5.0.3 on 2024-03-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0131_alter_questionn_company_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionn',
            name='company_profile',
        ),
    ]
