# Generated by Django 5.0.3 on 2024-03-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0134_rename_jobb_addaptitude_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaptitude',
            name='job_id',
        ),
    ]
