# Generated by Django 5.0.3 on 2024-03-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0135_remove_addaptitude_job_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddAptitude',
        ),
    ]
