# Generated by Django 5.0.3 on 2024-03-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0139_remove_questionn_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionn',
            name='company_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile'),
        ),
    ]
