# Generated by Django 5.0.3 on 2024-03-18 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0150_remove_addaptitude_job_id_addaptitude_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
            ],
        ),
    ]
