# Generated by Django 5.0.3 on 2024-03-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0151_examresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.questionn'),
        ),
    ]
