# Generated by Django 5.0.3 on 2024-03-20 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0157_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_question_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
                ('exam_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.examresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.questionn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
            ],
        ),
    ]
