# Generated by Django 5.0.3 on 2024-03-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0160_remove_responsenew_company_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='aptitude',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='response',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student_batch',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='student_phone',
        ),
    ]
