# Generated by Django 5.0.3 on 2024-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0164_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
