# Generated by Django 5.0.3 on 2024-03-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0165_testresult_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('marks', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
            ],
        ),
    ]
