# Generated by Django 5.0.3 on 2024-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0167_alter_shortlistedstudent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumebuilder',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='career_objective',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='certification1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='certification2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='certification3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='cgpa1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='cgpa2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='cgpa3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='git_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='internship1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='internship2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='internship3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='linkedin_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resumebuilder',
            name='soft_skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
