# Generated by Django 5.0.3 on 2024-03-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0169_resumebuilder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
