# Generated by Django 5.0.3 on 2024-03-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0170_examresponse_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
