# Generated by Django 5.0.3 on 2024-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0176_aptdresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptdresult',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
