# Generated by Django 5.0.3 on 2024-04-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0180_rename_studentt_interview_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='student',
        ),
    ]
