# Generated by Django 5.0.3 on 2024-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0182_aptdresult_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaptitude',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='aptitude_documents/'),
        ),
    ]
